## Numerical Computing with Numpy

In [11]:
import math

In [6]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [7]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [12]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples = math.ceil(kanto_yield_apples)

In [13]:
print(f'The expected yield of apples in kanto region is {kanto_yield_apples} tons per hectare')

The expected yield of apples in kanto region is 57 tons per hectare


In [9]:
import numpy as np

In [ ]:
np.array([73,])

In [40]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [42]:
weights = [w1, w2, w3]

In [16]:
kanto

[73, 67, 43]

In [18]:
weights

[0.3, 0.2, 0.5]

In [19]:
def crop_yield(region, weight):
    result  = 0
    for x, w in zip(region, weight):
        result += x * w
    return result

In [21]:
crop_yield(kanto, weights)

56.8

In [22]:
crop_yield(johto, weights)

76.9

In [23]:
crop_yield(unova, weights)

74.9

In [2]:
import numpy as np

In [25]:
kanto = np.array([73, 67, 43])

In [26]:
kanto

array([73, 67, 43])

In [51]:
weights = np.array([w1,w2,w3])

In [28]:
weights

array([0.3, 0.2, 0.5])

In [29]:
type(weights)

numpy.ndarray

In [30]:
type(kanto)

numpy.ndarray

In [31]:
weights[1]

np.float64(0.2)

In [32]:
kanto[2]

np.int64(43)

In [33]:
np.dot(kanto, weights)

np.float64(56.8)

In [34]:
kanto

array([73, 67, 43])

In [35]:
weights

array([0.3, 0.2, 0.5])

In [36]:
kanto * weights

array([21.9, 13.4, 21.5])

In [38]:
(kanto * weights).sum()

np.float64(56.8)

In [46]:
# for x, w in zip(kanto, weights):
#     print(x * w)

## Multidimensional Array

In [47]:
climate_data = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
])

In [48]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [49]:
climate_data.shape

(5, 3)

In [52]:
weights.shape

(3,)

In [63]:
# 3D array
arr3 = np.array([
    [[11,12,13],
    [13,14,15]],

    [[15,16,17],
    [17,18,19.5]]
])

In [56]:
arr3.shape

(2, 2, 3)

In [57]:
weights.dtype

dtype('float64')

In [59]:
climate_data.dtype

dtype('int64')

In [64]:
arr3.dtype

dtype('float64')

In [66]:
apple_yield = np.matmul(climate_data, weights)

In [69]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [68]:
apple_yield

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [67]:
apple_yield.shape

(5,)

In [72]:
climate_result = np.concatenate((climate_data, apple_yield.reshape(5,1)), axis = 1)

In [73]:
climate_result

array([[ 73. ,  67. ,  43. ,  56.8],
       [ 91. ,  88. ,  64. ,  76.9],
       [ 87. , 134. ,  58. ,  81.9],
       [102. ,  43. ,  37. ,  57.7],
       [ 69. ,  96. ,  70. ,  74.9]])

In [76]:
np.savetxt(
    'climate_result.txt',
    climate_result,
    fmt = '%.2f',
    header = 'temperature,rainfall,humidity,yeild_apples',
    comments = ''
)

In [3]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,1,2,3]
])

In [79]:
arr3 = np.array([
    [11,12,13,14],
    [15,16,17,18],
    [19,11,12,13]
])

In [81]:
arr2 + arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [80]:
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [82]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [83]:
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [84]:
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [85]:
arr2.shape

(3, 4)

In [4]:
arr4 = np.array([4,5,6,7])

In [5]:
arr4.shape

(4,)

In [87]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [7]:
arr5 = np.array([7,8])

In [8]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [9]:
arr1 = np.array([
    [1,2,3],
    [3,4,5]
])

arr2 = np.array([
    [2,2,3],
    [1,2,5]
])

In [10]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [11]:
(arr1 == arr2).dtype

dtype('bool')

In [13]:
(arr1 == arr2).sum() # to check the numbers that are equal

np.int64(3)

In [3]:
arr3 = np.array([
    [[11,12,13,14],
    [13,14,15,16]],

    [[15,16,17,21],
    [63,92,36,18]],

    [[98,32,81,23],
    [17,18,19.5,43]]
])

In [15]:
arr3.shape

(3, 2, 4)

In [4]:
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [5]:
arr3[1,1,2]

np.float64(36.0)

In [6]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [7]:
arr3[1:,1,3]

array([18., 43.])

## Other ways of creating Arrays

In [24]:
np.zeros((3,2)) # Passed in a tuple

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
np.eye(3) #Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.rand(6)

array([0.98629947, 0.44211365, 0.63638647, 0.4654628 , 0.04983869,
       0.55260931])

In [14]:
np.random.randn(2,3)

array([[-0.94613971, -0.88059135, -0.14309345],
       [ 0.02725907, -0.56719367,  1.1099252 ]])

In [15]:
np.arange(10,90,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85])

In [17]:
np.arange(10,90,5).shape

(16,)

In [20]:
np.arange(10,90,5).reshape(4,2,2)

array([[[10, 15],
        [20, 25]],

       [[30, 35],
        [40, 45]],

       [[50, 55],
        [60, 65]],

       [[70, 75],
        [80, 85]]])

In [22]:
np.linspace(3,27,12)

array([ 3.        ,  5.18181818,  7.36363636,  9.54545455, 11.72727273,
       13.90909091, 16.09090909, 18.27272727, 20.45454545, 22.63636364,
       24.81818182, 27.        ])